package gui;

import exceptions.TooManyToppingsException;
import io.MenuLoader;
import menu.MenuItem;
import menu.Order;
import pizza.CustomPizza;
import pizza.Pizza;
import pizza.ingredients.Bases;
import pizza.ingredients.Cheeses;
import pizza.ingredients.Sauces;
import pizza.ingredients.Topping;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.*;

/**
 * This class will <b>NOT</b> be tested and does <b>NOT</b> show great programming practices.
 *
 * @author Third Party Application provier
 */
public class Display extends javax.swing.JPanel {

    /* loads the menu from text file */
    private final menu.Menu menu = MenuLoader.load("PizzaMenu.txt");

    /* creates a new customer order string */
    private final StringBuilder currentOrderPanelString = new StringBuilder();

    /**
     * Launch the GUI
      * @param args Ignored
     */
    public static void main(String[] args) {
        new Display();
    }

    public Display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        JFrame frame = new JFrame("Display");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1440, 900);
        frame.setVisible(true);

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel23 = new javax.swing.JPanel();
        selectToppingsPanel = new javax.swing.JPanel();
        toppingsComboBox = new javax.swing.JComboBox<>();
        clearToppingButton = new java.awt.Button();
        addPizzaButton = new java.awt.Button();
        createTotalPrice = new javax.swing.JLabel();
        toppingButtonAdd = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        toppingLabel1 = new javax.swing.JLabel();
        toppingLabel3 = new javax.swing.JLabel();
        toppingLabel4 = new javax.swing.JLabel();
        toppingLabel5 = new javax.swing.JLabel();
        toppingLabel2 = new javax.swing.JLabel();
        toppingXButton1 = new javax.swing.JButton();
        toppingXButton2 = new javax.swing.JButton();
        toppingXButton3 = new javax.swing.JButton();
        toppingXButton4 = new javax.swing.JButton();
        toppingXButton5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        createTomatoRadioButton = new javax.swing.JRadioButton();
        createTomatoRadioButton.setSelected(true);
        createBBQRadioButton = new javax.swing.JRadioButton();
        createGarlicRadioButton = new javax.swing.JRadioButton();
        createNoneSauceRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        createMozzerallaRadioButton = new javax.swing.JRadioButton();
        createMozzerallaRadioButton.setSelected(true);
        createVeganRadioButton = new javax.swing.JRadioButton();
        createNoneCheeseRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        createSmallRadioButton = new javax.swing.JRadioButton();
        createMediumRadioButton = new javax.swing.JRadioButton();
        createMediumRadioButton.setSelected(true);
        createLargeRadioButton = new javax.swing.JRadioButton();
        createSizePrice = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        jLabel33 = new javax.swing.JLabel();
        selectPrice = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        selectMozzerallaRadioButton = new javax.swing.JRadioButton();
        selectMozzerallaRadioButton.setSelected(true);
        selectVeganRadioButton = new javax.swing.JRadioButton();
        selectNoneCheeseRadioButton = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        selectTomatoRadioButton = new javax.swing.JRadioButton();
        selectTomatoRadioButton.setSelected(true);
        selectBBQRadioButton = new javax.swing.JRadioButton();
        selectGarlicRadioButton = new javax.swing.JRadioButton();
        selectNoneSauceRadioButton = new javax.swing.JRadioButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        selectSmallRadioButton = new javax.swing.JRadioButton();
        selectMediumRadioButton = new javax.swing.JRadioButton();
        selectMediumRadioButton.setSelected(true);
        selectLargeRadioButton = new javax.swing.JRadioButton();
        selectSizePrice = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Current Order"));

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Cancel All");
        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jTextArea1.setText("");
                jTextArea2.setText("");
                order = new Order();
                orders.clear();
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 204, 0));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Confirm");
        jButton4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                order.setTime(LocalTime.now());
                order.setDate(LocalDate.now());
                orders.add(order);
                order = new Order();
                jTextArea2.setText("");
                StringJoiner joiner =
                    new StringJoiner(System.lineSeparator() + System.lineSeparator());
                for (Order o : orders) {
                    joiner.add(o.toString());
                }
                jTextArea1.setText(joiner.toString());
            }
        });

        jTextArea2.setBackground(new java.awt.Color(255, 204, 204));
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));

        jTextArea1.setText("Your placed orders will appear here.");
        jTextArea2.setColumns(100);
        jTextArea2.setRows(500);

        jScrollPane2.setViewportView(jTextArea2);
        jTextArea2.getAccessibleContext().setAccessibleParent(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(482, Short.MAX_VALUE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3)
                                        .addComponent(jButton4))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(51, 255, 51));
        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel23.setBackground(new java.awt.Color(204, 204, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create a custom pizza", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        selectToppingsPanel.setBackground(new java.awt.Color(255, 255, 255));
        selectToppingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Toppings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        toppingsComboBox.setBackground(new java.awt.Color(153, 255, 153));


        // Sets the combo list to be the list of toppings
        toppingsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                // get array of string which are the names from Topping values()
                Arrays.stream(Topping.values()).map(Topping::toString).toArray(String[]::new)));

        clearToppingButton.setActionCommand("cancelMenuItemButton");
        clearToppingButton.setBackground(new java.awt.Color(255, 102, 102));
        clearToppingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clearToppingButton.setLabel("Clear Topping");
        clearToppingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearToppingActionPerformed(evt);
            }
        });

        addPizzaButton.setActionCommand("addMenuItemButton");
        addPizzaButton.setBackground(new java.awt.Color(51, 204, 0));
        addPizzaButton.setLabel("Add Pizza");
        addPizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPizzaActionPerformed(evt);
            }
        });

        createTotalPrice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        createTotalPrice.setForeground(new java.awt.Color(0, 0, 0));
        createTotalPrice.setText("$15.00");

        toppingButtonAdd.setBackground(new java.awt.Color(51, 204, 0));
        toppingButtonAdd.setForeground(new java.awt.Color(0, 0, 0));
        toppingButtonAdd.setText("+");
        toppingButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toppingButtonAddActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        toppingLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        toppingLabel1.setForeground(new java.awt.Color(0, 0, 0));
        toppingLabel1.setText("L1, $2.00");

        toppingLabel3.setBackground(new java.awt.Color(0, 0, 0));
        toppingLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        toppingLabel3.setForeground(new java.awt.Color(0, 0, 0));
        toppingLabel3.setText("L3 $2.00");

        toppingLabel4.setBackground(new java.awt.Color(0, 0, 0));
        toppingLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        toppingLabel4.setForeground(new java.awt.Color(0, 0, 0));
        toppingLabel4.setText("L4 $2.00");

        toppingLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        toppingLabel5.setForeground(new java.awt.Color(0, 0, 0));
        toppingLabel5.setText("L5, $2.00");

        toppingLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        toppingLabel2.setForeground(new java.awt.Color(0, 0, 0));
        toppingLabel2.setText("L2, $2.00");

        toppingXButton1.setBackground(new java.awt.Color(255, 102, 102));
        toppingXButton1.setForeground(new java.awt.Color(0, 0, 0));
        toppingXButton1.setText("X");
        toppingXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toppingXButton1ActionPerformed(evt);
            }
        });

        toppingXButton2.setBackground(new java.awt.Color(255, 102, 102));
        toppingXButton2.setForeground(new java.awt.Color(0, 0, 0));
        toppingXButton2.setText("X");
        toppingXButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toppingXButton2ActionPerformed(evt);
            }
        });

        toppingXButton3.setBackground(new java.awt.Color(255, 102, 102));
        toppingXButton3.setForeground(new java.awt.Color(0, 0, 0));
        toppingXButton3.setText("X");
        toppingXButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toppingXButton3ActionPerformed(evt);
            }
        });

        toppingXButton4.setBackground(new java.awt.Color(255, 102, 102));
        toppingXButton4.setForeground(new java.awt.Color(0, 0, 0));
        toppingXButton4.setText("X");
        toppingXButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toppingXButton4ActionPerformed(evt);
            }
        });

        toppingXButton5.setBackground(new java.awt.Color(255, 102, 102));
        toppingXButton5.setForeground(new java.awt.Color(0, 0, 0));
        toppingXButton5.setText("X");
        toppingXButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toppingXButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(toppingXButton1)
                                        .addComponent(toppingXButton2)
                                        .addComponent(toppingXButton3)
                                        .addComponent(toppingXButton4)
                                        .addComponent(toppingXButton5))
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(toppingLabel3)
                                                        .addComponent(toppingLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(toppingLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(toppingLabel4))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(toppingLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(toppingXButton1)
                                        .addComponent(toppingLabel1))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(toppingXButton2)
                                        .addComponent(toppingLabel2))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(toppingXButton3)
                                        .addComponent(toppingLabel3))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(toppingXButton4)
                                        .addComponent(toppingLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(toppingXButton5)
                                        .addComponent(toppingLabel5))
                                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(selectToppingsPanel);
        selectToppingsPanel.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(toppingsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(toppingButtonAdd))
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel8Layout.createSequentialGroup()
                                                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addGap(53, 53, 53)
                                                        .addComponent(createTotalPrice))
                                                .addGroup(jPanel8Layout.createSequentialGroup()
                                                        .addComponent(clearToppingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(addPizzaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(toppingsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(toppingButtonAdd))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(createTotalPrice))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(clearToppingButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addPizzaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sauce", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        buttonGroup2.add(createTomatoRadioButton);

        buttonGroup2.add(createBBQRadioButton);

        buttonGroup2.add(createGarlicRadioButton);

        buttonGroup2.add(createNoneSauceRadioButton);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tomato");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("BBQ");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Garlic");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("None");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(createNoneSauceRadioButton))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(createGarlicRadioButton))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(createBBQRadioButton))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(createTomatoRadioButton)))
                                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(createTomatoRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(createBBQRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(createGarlicRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(createNoneSauceRadioButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cheese", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        jPanel24.setBackground(new java.awt.Color(255, 204, 153));

        buttonGroup1.add(createMozzerallaRadioButton);
        createMozzerallaRadioButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        buttonGroup1.add(createVeganRadioButton);
        createVeganRadioButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        buttonGroup1.add(createNoneCheeseRadioButton);
        createNoneCheeseRadioButton.setToolTipText("");
        createNoneCheeseRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createNoneCheeseRadioButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mozzarella");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Vegan");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("None");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
                jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(createNoneCheeseRadioButton)
                                        .addComponent(createMozzerallaRadioButton)
                                        .addComponent(createVeganRadioButton))
                                .addGap(18, 18, 18))
        );
        jPanel24Layout.setVerticalGroup(
                jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel24Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel24Layout.createSequentialGroup()
                                                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(createMozzerallaRadioButton)
                                                        .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3))
                                        .addComponent(createVeganRadioButton))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(createNoneCheeseRadioButton))
                                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Size", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Small");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Medium");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Large");

        buttonGroup3.add(createSmallRadioButton);
        buttonGroup3.add(createMediumRadioButton);

        buttonGroup3.add(createLargeRadioButton);

        createSizePrice.setBackground(new java.awt.Color(0, 0, 0));
        createSizePrice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        createSizePrice.setForeground(new java.awt.Color(0, 0, 0));
        createSizePrice.setText("$5.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(jLabel13)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(
                                                                    createLargeRadioButton))
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(jLabel11)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(
                                                                    createSmallRadioButton))
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(jLabel12)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(
                                                                    createMediumRadioButton))))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(createSizePrice)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(createSmallRadioButton)
                                        .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(createMediumRadioButton)
                                                .addGap(4, 4, 4)
                                                .addComponent(createLargeRadioButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createSizePrice)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("<html>Please create your pizza and the preference for Cheese, <br>Sauce and Size. Add up to 5 toppings. The Size selected will alter the menu price.</html> ");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
                jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel23Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel23Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(selectToppingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
                jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectToppingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create Pizza", jPanel23);

        jPanel25.setBackground(new java.awt.Color(255, 255, 102));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose a Pizza from the menu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Select", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jComboBox3.setBackground(new java.awt.Color(153, 255, 153));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(
                menu.getItems().stream().map(MenuItem::getName).toArray(String[]::new)));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                String selected = (String) jComboBox3.getSelectedItem(); // get the selected item
                //  gets the selected menUItem from the list of Menu Items in the menu
                MenuItem mu = menu.getItems().stream().filter((menu.MenuItem t)
                    -> t.getName().equals(selected)).findFirst().get();
                Bases.BaseSize size = Bases.BaseSize.MEDIUM;
                if (selectMediumRadioButton.isSelected()) {
                    size = Bases.BaseSize.MEDIUM;
                } else if (selectSmallRadioButton.isSelected()) {
                    size = Bases.BaseSize.SMALL;
                } else if (selectLargeRadioButton.isSelected()) {
                    size = Bases.BaseSize.LARGE;
                }
                ((Pizza)mu).set(size);
                String sel = mu.toString(); // get the first item that matches the selected item
                selectPrice.setText(String.format("$%.2f",mu.getTotalPrice()));
                jComboBox3ActionPerformed(sel);
            }
        });

        button5.setActionCommand("cancelMenuItemButton");
        button5.setBackground(new java.awt.Color(255, 102, 102));
        button5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button5.setLabel("Cancel Order");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });


        button6.setActionCommand("addMenuItemButton");
        button6.setBackground(new java.awt.Color(51, 204, 0));
        button6.setLabel("Add Pizza");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAddPizzaButtonActionListener(evt);
            }
        });

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("");//Spicy Italian [Pepperoni, Jalapeno, Peppers] + $6.00");

        selectPrice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        selectPrice.setForeground(new java.awt.Color(0, 0, 0));
        selectPrice.setText("");// $11.00");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
                jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel26Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel26Layout.createSequentialGroup()
                                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(selectPrice)
                                                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel26Layout.createSequentialGroup()
                                                                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 12, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
                jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel26Layout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(selectPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        selectSmallRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                selectSizePrice.setText(String.format("$%.2f", Bases.BaseSize.SMALL.getPrice()));
                String selected = (String) jComboBox3.getSelectedItem();

                //  gets the selected menUItem from the list of Menu Items in the menu
                MenuItem mu = menu.getItems().stream().filter((menu.MenuItem t)
                    -> t.getName().equals(selected)).findFirst().get();
                ((Pizza)mu).set(Bases.BaseSize.SMALL);
                selectPrice.setText(String.format("$%.2f",mu.getTotalPrice()));

            }
        });
        selectMediumRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                selectSizePrice.setText(String.format("$%.2f", Bases.BaseSize.MEDIUM.getPrice()));
                String selected = (String) jComboBox3.getSelectedItem();

                //  gets the selected menUItem from the list of Menu Items in the menu
                MenuItem mu = menu.getItems().stream().filter((menu.MenuItem t)
                    -> t.getName().equals(selected)).findFirst().get();
                ((Pizza)mu).set(Bases.BaseSize.MEDIUM);
                selectPrice.setText(String.format("$%.2f",mu.getTotalPrice()));
            }
        });
        selectLargeRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                selectSizePrice.setText(String.format("$%.2f", Bases.BaseSize.LARGE.getPrice()));
                String selected = (String) jComboBox3.getSelectedItem();

                //  gets the selected menUItem from the list of Menu Items in the menu
                MenuItem mu = menu.getItems().stream().filter((menu.MenuItem t)
                    -> t.getName().equals(selected)).findFirst().get();
                ((Pizza)mu).set(Bases.BaseSize.LARGE);
                selectPrice.setText(String.format("$%.2f",mu.getTotalPrice()));
            }
        });

        createSmallRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                createSizePrice.setText(String.format("$%.2f", Bases.BaseSize.SMALL.getPrice()));
                updateToppingsLabelAndButton();
            }
        });
        createMediumRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                createSizePrice.setText(String.format("$%.2f", Bases.BaseSize.MEDIUM.getPrice()));
                updateToppingsLabelAndButton();
            }
        });
        createLargeRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                createSizePrice.setText(String.format("$%.2f", Bases.BaseSize.LARGE.getPrice()));
                updateToppingsLabelAndButton();
            }
        });

        jPanel27.setBackground(new java.awt.Color(255, 255, 102));

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cheese", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel28.setForeground(new java.awt.Color(0, 0, 0));

        jPanel29.setBackground(new java.awt.Color(255, 204, 153));

        buttonGroup4.add(selectMozzerallaRadioButton);
        selectMozzerallaRadioButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        buttonGroup4.add(selectVeganRadioButton);
        selectVeganRadioButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        buttonGroup4.add(selectNoneCheeseRadioButton);
        selectNoneCheeseRadioButton.setToolTipText("");
        selectNoneCheeseRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectNoneCheeseRadioButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Mozzarella");

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Vegan");

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("None");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
                jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                                .addContainerGap(14, Short.MAX_VALUE)
                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel36)
                                        .addComponent(jLabel35)
                                        .addComponent(jLabel37))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(selectNoneCheeseRadioButton)
                                        .addComponent(selectMozzerallaRadioButton)
                                        .addComponent(selectVeganRadioButton))
                                .addGap(18, 18, 18))
        );
        jPanel29Layout.setVerticalGroup(
                jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel29Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel29Layout.createSequentialGroup()
                                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(selectMozzerallaRadioButton)
                                                        .addComponent(jLabel35))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel36))
                                        .addComponent(selectVeganRadioButton))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel37)
                                        .addComponent(selectNoneCheeseRadioButton))
                                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
                jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel28Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel28Layout.setVerticalGroup(
                jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel28Layout.createSequentialGroup()
                                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sauce", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jPanel31.setBackground(new java.awt.Color(204, 255, 255));

        buttonGroup5.add(selectTomatoRadioButton);

        buttonGroup5.add(selectBBQRadioButton);

        buttonGroup5.add(selectGarlicRadioButton);

        buttonGroup5.add(selectNoneSauceRadioButton);

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Tomato");

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("BBQ");

        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Garlic");

        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("None");

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
                jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel31Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel31Layout.createSequentialGroup()
                                                .addComponent(jLabel41)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(selectNoneSauceRadioButton))
                                        .addGroup(jPanel31Layout.createSequentialGroup()
                                                .addComponent(jLabel40)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(selectGarlicRadioButton))
                                        .addGroup(jPanel31Layout.createSequentialGroup()
                                                .addComponent(jLabel39)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(selectBBQRadioButton))
                                        .addGroup(jPanel31Layout.createSequentialGroup()
                                                .addComponent(jLabel38)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(selectTomatoRadioButton)))
                                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel31Layout.setVerticalGroup(
                jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel31Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel38)
                                        .addComponent(selectTomatoRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel39)
                                        .addComponent(selectBBQRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel40)
                                        .addComponent(selectGarlicRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel41)
                                        .addComponent(selectNoneSauceRadioButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
                jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel30Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
                jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                                .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Size", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        jPanel33.setBackground(new java.awt.Color(255, 204, 204));

        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Small");

        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Medium");

        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Large");

        buttonGroup6.add(selectSmallRadioButton);
        buttonGroup6.add(selectMediumRadioButton);

        buttonGroup6.add(selectLargeRadioButton);

        selectSizePrice.setBackground(new java.awt.Color(0, 0, 0));
        selectSizePrice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        selectSizePrice.setForeground(new java.awt.Color(0, 0, 0));
        selectSizePrice.setText("$5.00");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
                jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel33Layout.createSequentialGroup()
                                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel33Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel33Layout.createSequentialGroup()
                                                                .addComponent(jLabel44)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(
                                                                    selectLargeRadioButton))
                                                        .addGroup(jPanel33Layout.createSequentialGroup()
                                                                .addComponent(jLabel42)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(
                                                                    selectSmallRadioButton))
                                                        .addGroup(jPanel33Layout.createSequentialGroup()
                                                                .addComponent(jLabel43)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(
                                                                    selectMediumRadioButton))))
                                        .addGroup(jPanel33Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(selectSizePrice)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
                jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel33Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(selectSmallRadioButton)
                                        .addComponent(jLabel42))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel33Layout.createSequentialGroup()
                                                .addComponent(jLabel43)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel44))
                                        .addGroup(jPanel33Layout.createSequentialGroup()
                                                .addComponent(selectMediumRadioButton)
                                                .addGap(4, 4, 4)
                                                .addComponent(selectLargeRadioButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectSizePrice)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
                jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel32Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
                jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                                .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
                jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel27Layout.createSequentialGroup()
                                .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
                jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("<html>Please select the menu pizza and the preference for Cheese, <br>Sauce and Size.  The Size selected will alter the menu price.</html> ");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
                jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel25Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 81, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
                jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(213, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Select Pizza", jPanel25);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Orders Placed"));

        jTextArea1.setBackground(new java.awt.Color(153, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
                jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
                jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("Orders Placed", jPanel22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTabbedPane1)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addContainerGap(8, Short.MAX_VALUE))
        );
        frame.add(this);
        toppingLabels = new JLabel[] {
            toppingLabel1, toppingLabel2, toppingLabel3, toppingLabel4, toppingLabel5
        };
        toppingButtons = new JButton[] {
            toppingXButton1, toppingXButton2, toppingXButton3, toppingXButton4, toppingXButton5
        };
        updateToppingsLabelAndButton();
    }// </editor-fold>

    private void clearToppingActionPerformed(java.awt.event.ActionEvent evt) {
        toppings.clear();
        updateToppingsLabelAndButton();
    }

    private void addPizzaActionPerformed(java.awt.event.ActionEvent evt) {
        Bases.BaseSize size = Bases.BaseSize.MEDIUM;
        if (createMediumRadioButton.isSelected()) {
            size = Bases.BaseSize.MEDIUM;
        } else if (createSmallRadioButton.isSelected()) {
            size = Bases.BaseSize.SMALL;
        } else if (createLargeRadioButton.isSelected()) {
            size = Bases.BaseSize.LARGE;
        }
        Cheeses.Cheese cheese = Cheeses.Cheese.MOZZARELLA;
        if (createMozzerallaRadioButton.isSelected()) {
            cheese = Cheeses.Cheese.MOZZARELLA;
        } else if (createVeganRadioButton.isSelected()) {
            cheese = Cheeses.Cheese.VEGAN;
        } else if (createNoneCheeseRadioButton.isSelected()) {
            cheese = Cheeses.Cheese.NONE;
        }
        Sauces.Sauce sauce = Sauces.Sauce.TOMATO;
        if (createTomatoRadioButton.isSelected()) {
            sauce = Sauces.Sauce.TOMATO;
        } else if (createBBQRadioButton.isSelected()) {
            sauce = Sauces.Sauce.BBQ;
        } else if (createGarlicRadioButton.isSelected()) {
            sauce = Sauces.Sauce.GARLIC;
        } else if (createNoneSauceRadioButton.isSelected()) {
            sauce = Sauces.Sauce.NONE;
        }
        CustomPizza pizza = new CustomPizza(size, sauce, cheese);
        try {
            pizza.add(toppings);
        } catch (TooManyToppingsException e) {
            e.printStackTrace();
        }
        order.add(pizza);
        updateCurrentOrder(pizza.toString()+"\n");
        toppings.clear();
        updateToppingsLabelAndButton();
    }

    private List<Topping> toppings = new ArrayList<>();

    private void updateToppingsLabelAndButton() {
        Bases.BaseSize size = Bases.BaseSize.MEDIUM;
        if (createMediumRadioButton.isSelected()) {
            size = Bases.BaseSize.MEDIUM;
        } else if (createSmallRadioButton.isSelected()) {
            size = Bases.BaseSize.SMALL;
        } else if (createLargeRadioButton.isSelected()) {
            size = Bases.BaseSize.LARGE;
        }
        for (int i = 0; i < Pizza.MAX_TOPPINGS; i++) {
            JLabel label = toppingLabels[i];
            JButton button = toppingButtons[i];
            try {
                Topping topping = toppings.get(i);
                label.setText(topping.toString());
                label.setVisible(true);
                button.setVisible(true);
            } catch (IndexOutOfBoundsException e) {
                label.setVisible(false);
                button.setVisible(false);
            }
        }
        createTotalPrice.setText(String.format("$%.2f", size.getPrice() + toppings.size() * 2));
    }

    private void toppingButtonAddActionPerformed(java.awt.event.ActionEvent evt) {
        if(toppings.size() == Pizza.MAX_TOPPINGS) {
            return;
        }
        String toppingName = (String) toppingsComboBox.getSelectedItem();
        try {
            toppings.add(Topping.valueOf(toppingName));
        } catch (Exception e) {
            System.out.println("Something went wrong with Topping#valueOf");
            System.exit(1);
        }
        updateToppingsLabelAndButton();
    }

    /**
     * Action method for comboBox3, takes a String for the text to be changed
     *
     * @param text String
     *
     */
    private void jComboBox3ActionPerformed(String text) {
        menuItemSelection = text; // set the global variable for use when button is clicked

        text = text.replace("[MenuPizza]", "");

        String name = text.substring(0, text.indexOf(":"));
        String price = text.substring(text.indexOf("$") - 1);
        String toppings = "";
        try {
            toppings = text.substring(text.indexOf("[") + 1, text.indexOf("]"));
        }catch (StringIndexOutOfBoundsException ignored) {
            // no toppings
        }
        selectPrice.setText(price);
        jLabel33.setText(String.format("%s : %s", name, toppings));
    }

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {
        jTextArea2.setText("");
        order = new Order();
    }

    private String menuItemSelection = null;

    Order order = new Order();
    List<Order> orders = new ArrayList<>();
    private void selectAddPizzaButtonActionListener(java.awt.event.ActionEvent evt) {
        String selected = (String) jComboBox3.getSelectedItem();

        //  gets the selected menUItem from the list of Menu Items in the menu
        MenuItem mu = menu.getItems().stream().filter((menu.MenuItem t)
                -> t.getName().equals(selected)).findFirst().get();
        Bases.BaseSize size = Bases.BaseSize.MEDIUM;
        if (selectMediumRadioButton.isSelected()) {
            size = Bases.BaseSize.MEDIUM;
        } else if (selectSmallRadioButton.isSelected()) {
            size = Bases.BaseSize.SMALL;
        } else if (selectLargeRadioButton.isSelected()) {
            size = Bases.BaseSize.LARGE;
        }
        Cheeses.Cheese cheese = Cheeses.Cheese.MOZZARELLA;
        if (selectMozzerallaRadioButton.isSelected()) {
            cheese = Cheeses.Cheese.MOZZARELLA;
        } else if (selectVeganRadioButton.isSelected()) {
            cheese = Cheeses.Cheese.VEGAN;
        } else if (selectNoneCheeseRadioButton.isSelected()) {
            cheese = Cheeses.Cheese.NONE;
        }
        Sauces.Sauce sauce = Sauces.Sauce.TOMATO;
        if (selectTomatoRadioButton.isSelected()) {
            sauce = Sauces.Sauce.TOMATO;
        } else if (selectBBQRadioButton.isSelected()) {
            sauce = Sauces.Sauce.BBQ;
        } else if (selectGarlicRadioButton.isSelected()) {
            sauce = Sauces.Sauce.GARLIC;
        } else if (selectNoneSauceRadioButton.isSelected()) {
            sauce = Sauces.Sauce.NONE;
        }
        // add mu to order
        Pizza pizza = (Pizza) mu;
        pizza.set(size);
        pizza.set(sauce);
        pizza.set(cheese);
        order.add(pizza);
        updateCurrentOrder(pizza.toString()+"\n");
    }

    private void toppingXButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        toppings.remove(Topping.valueOf(toppingLabel1.getText()));
        updateToppingsLabelAndButton();
    }
    private void toppingXButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        toppings.remove(Topping.valueOf(toppingLabel2.getText()));
        updateToppingsLabelAndButton();
    }
    private void toppingXButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        toppings.remove(Topping.valueOf(toppingLabel3.getText()));
        updateToppingsLabelAndButton();
    }
    private void toppingXButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        toppings.remove(Topping.valueOf(toppingLabel4.getText()));
        updateToppingsLabelAndButton();
    }
    private void toppingXButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        toppings.remove(Topping.valueOf(toppingLabel5.getText()));
        updateToppingsLabelAndButton();
    }

    /**
     * adds the order String (representing the entire order)
     * to the Text area (Current Order)
     */
    private void updateCurrentOrder(String order) {
        jTextArea2.insert(order.toString(), 0);
    }

    // Variables declaration - do not modify
    private java.awt.Button addPizzaButton;
    private java.awt.Button clearToppingButton;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton toppingButtonAdd;
    private javax.swing.JButton toppingXButton1;
    private javax.swing.JButton toppingXButton2;
    private javax.swing.JButton toppingXButton3;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton toppingXButton4;
    private javax.swing.JButton toppingXButton5;
    private javax.swing.JComboBox<String> toppingsComboBox;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel toppingLabel1;
    private javax.swing.JLabel createSizePrice;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel toppingLabel4;
    private javax.swing.JLabel toppingLabel3;
    private javax.swing.JLabel toppingLabel5;
    private javax.swing.JLabel toppingLabel2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel selectPrice;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel selectSizePrice;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel createTotalPrice;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel selectToppingsPanel;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton createMozzerallaRadioButton;
    private javax.swing.JRadioButton createLargeRadioButton;
    private javax.swing.JRadioButton createVeganRadioButton;
    private javax.swing.JRadioButton selectMozzerallaRadioButton;
    private javax.swing.JRadioButton selectVeganRadioButton;
    private javax.swing.JRadioButton selectNoneCheeseRadioButton;
    private javax.swing.JRadioButton selectTomatoRadioButton;
    private javax.swing.JRadioButton selectBBQRadioButton;
    private javax.swing.JRadioButton selectGarlicRadioButton;
    private javax.swing.JRadioButton selectNoneSauceRadioButton;
    private javax.swing.JRadioButton selectSmallRadioButton;
    private javax.swing.JRadioButton selectMediumRadioButton;
    private javax.swing.JRadioButton createNoneCheeseRadioButton;
    private javax.swing.JRadioButton selectLargeRadioButton;
    private javax.swing.JRadioButton createTomatoRadioButton;
    private javax.swing.JRadioButton createBBQRadioButton;
    private javax.swing.JRadioButton createGarlicRadioButton;
    private javax.swing.JRadioButton createNoneSauceRadioButton;
    private javax.swing.JRadioButton createSmallRadioButton;
    private javax.swing.JRadioButton createMediumRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;

    private JLabel[] toppingLabels;
    private JButton[] toppingButtons;

    // End of variables declaration
}
